
import { ScheduleItem } from './types';

// Helper to generate a consistent ID based on content
const generateId = (item: any) => {
    return `${item.bloco}-${item.aula}-${item.professor}`.replace(/\s+/g, '-').toLowerCase();
};

const RAW_DATA = [
    // Bloco 1
    { bloco: "1", aula: "Avaliação Global do Hemograma", professor: "Marco Aurélio Campanha Sartori", disciplina: "Hematologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "1", aula: "Anemias Hipoproliferativas I", professor: "Marco Aurélio Campanha Sartori", disciplina: "Hematologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "1", aula: "Anemias Hipoproliferativas II", professor: "Marco Aurélio Campanha Sartori", disciplina: "Hematologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "1", aula: "Modificações do Organismo Materno", professor: "Nicole Kemberly Ribeiro Rocha", disciplina: "Obstetrícia Básico", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "1", aula: "Assistência ao Pré-Natal", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Básico", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "1", aula: "Ultrassonografia em Obstetrícia", professor: "Gelson Farias Arcos Júnior", disciplina: "Medicina fetal", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "1", aula: "Aleitamento Materno", professor: "Amira Kheireddine Saleh", disciplina: "Puericultura", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "1", aula: "Alimentação Infantil", professor: "Amira Kheireddine Saleh", disciplina: "Puericultura", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "1", aula: "Desenvolvimento Infantil", professor: "Amira Kheireddine Saleh", disciplina: "Puericultura", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "1", aula: "Alterações no Neurodesenvolvimento - TEA e TDAH", professor: "José Marcos Vieira de Albuquerque Filho", disciplina: "Neuro-Ped", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "1", aula: "Boas Vindas à Preventiva", professor: "Darizon José de Oliveira Filho", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "1", aula: "Níveis de Prevenção", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "1", aula: "Indicadores de Saúde", professor: "Luana Alves Suleiman", disciplina: "Epidemiologia", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "1", aula: "Introdução ao Extensivo e Como Acertar Questões", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "1", aula: "Introdução ao Trauma e Atendimento Inicial", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "1", aula: "Trauma: Vias aéreas", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "1", aula: "Choque e Ressuscitação Hemostática", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Verde" },

    // Bloco 2
    { bloco: "2", aula: "Neurovascular I: AIT e AVCi", professor: "Leonardo de Sousa Bernardes", disciplina: "Neurologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "2", aula: "Neurovascular II : HSA e AVCh", professor: "Leonardo de Sousa Bernardes", disciplina: "Neurologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "2", aula: "Anatomia Pélvica Feminina", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "2", aula: "Embriologia do Sistema Genital Feminino", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "2", aula: "Malformações Mullerianas", professor: "Nicole Kemberly Ribeiro Rocha", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "2", aula: "Febre sem Sinais Localizatórios", professor: "Laura Coimbra Teixeira", disciplina: "Emergências Pediátricas", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "2", aula: "Síndrome Nefrítica, Nefrótica, SHU", professor: "Laura Coimbra Teixeira", disciplina: "Esp. Ped: Nefrologia", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "2", aula: "Doença Renal Crônica e Lesão Renal Aguda", professor: "Laura Coimbra Teixeira", disciplina: "Esp. Ped: Nefrologia", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "2", aula: "Miscelânea em Nefropediatria", professor: "Laura Coimbra Teixeira", disciplina: "Esp. Ped: Nefrologia", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "2", aula: "Testes Diagnósticos", professor: "Darizon José de Oliveira Filho", disciplina: "Epidemiologia", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "2", aula: "Assistência ao Pré-Natal na APS", professor: "Nathália Machado Cardoso", disciplina: "MFC", grandeArea: "Preventiva", importancia: "Amarelo" },
    { bloco: "2", aula: "Trauma: Medidas Auxiliares e FAST", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "2", aula: "Trauma: Populações especiais", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "2", aula: "Trauma de Tórax", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },

    // Bloco 3
    { bloco: "3", aula: "Sífilis", professor: "Jaqueline Fabiano Palazzo", disciplina: "Infectologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "3", aula: "Dispepsia, DRGE e Barret", professor: "Rafael Bandeira Lages", disciplina: "Gastroenterologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "3", aula: "Úlcera péptica, H. pylori...", professor: "Rafael Bandeira Lages", disciplina: "Gastroenterologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "3", aula: "Corrimentos Vaginais", professor: "Nicole Kemberly Ribeiro Rocha", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "3", aula: "Doença Inflamatória Pélvica Aguda", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "3", aula: "Úlceras Genitais", professor: "Nicole Kemberly Ribeiro Rocha", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "3", aula: "Alergia Alimentar, Refluxo e Constipação", professor: "Camilla Silva Castro e Sousa", disciplina: "Esp. Ped: Gastro", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "3", aula: "Diarreia Crônica e Doenças Funcionais", professor: "Camilla Silva Castro e Sousa", disciplina: "Esp. Ped: Gastro", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "3", aula: "Violência Contra a Criança e o Adolescente", professor: "Camilla Silva Castro e Sousa", disciplina: "Emergências Pediátricas", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "3", aula: "Determinação Social do Processo Saúde-Doença", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "3", aula: "Trauma Abdominal", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "3", aula: "Trauma Urológico", professor: "Matheus Tiseu Ruggeri", disciplina: "Urologia", grandeArea: "Cirurgia", importancia: "Amarelo" },

    // Bloco 4
    { bloco: "4", aula: "Introdução às Artrites e AR", professor: "Henrique Helson Herter Dalmolin", disciplina: "Reumatologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "4", aula: "Espondiloartrites", professor: "Henrique Helson Herter Dalmolin", disciplina: "Reumatologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "4", aula: "Artrites Microcristalinas", professor: "Henrique Helson Herter Dalmolin", disciplina: "Reumatologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "4", aula: "Osteoartrite", professor: "Henrique Helson Herter Dalmolin", disciplina: "Reumatologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "4", aula: "Fibromialgia", professor: "Henrique Helson Herter Dalmolin", disciplina: "Reumatologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "4", aula: "Assistência ao Parto", professor: "Graciella Calsolari Figueiredo de Farias", disciplina: "Obstetrícia Básico", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "4", aula: "Sofrimento Fetal Agudo", professor: "Gelson Farias Arcos Júnior", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "4", aula: "Crescimento e Baixa Estatura", professor: "Roberta de Oliveira Andrade", disciplina: "Puericultura", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "4", aula: "Obesidade e Síndrome Metabólica", professor: "Roberta de Oliveira Andrade", disciplina: "Puericultura", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "4", aula: "Puberdade", professor: "Roberta de Oliveira Andrade", disciplina: "Puericultura", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "4", aula: "Desnutrição e Vitaminas", professor: "Roberta de Oliveira Andrade", disciplina: "Puericultura", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "4", aula: "Redes de Atenção à Saúde", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "4", aula: "Atenção Primária à Saúde", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "4", aula: "Trauma de Pelve", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "4", aula: "Trauma Cranioencefálico", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "4", aula: "Trauma Raquimedular", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Amarelo" },
    { bloco: "4", aula: "Trauma Musculoesquelético", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "4", aula: "Trauma de Pescoço", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Vermelho" },

    // Bloco 5
    { bloco: "5", aula: "Dor Torácica Coronariana", professor: "Julia Pereira Afonso dos Santos Tormin", disciplina: "Cardiologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "5", aula: "Dor Torácica Não Coronariana", professor: "Julia Pereira Afonso dos Santos Tormin", disciplina: "Cardiologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "5", aula: "Fisiologia Menstrual", professor: "Nicole Kemberly Ribeiro Rocha", disciplina: "Ginecologia Endócrina", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "5", aula: "Amenorreia Primária", professor: "Nicole Kemberly Ribeiro Rocha", disciplina: "Ginecologia Endócrina", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "5", aula: "Esteroidogênese", professor: "Nicole Kemberly Ribeiro Rocha", disciplina: "Ginecologia Endócrina", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "5", aula: "Politrauma, Afogamento", professor: "Thais Renata Hollanders dos Santos Fiani", disciplina: "Intensiva Pediátrica", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "5", aula: "Queimaduras", professor: "Thais Renata Hollanders dos Santos Fiani", disciplina: "Intensiva Pediátrica", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "5", aula: "Traumatismo Cranioentecefálico e HIC", professor: "Thais Renata Hollanders dos Santos Fiani", disciplina: "Intensiva Pediátrica", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "5", aula: "Diarreia Aguda", professor: "Roberta de Oliveira Andrade", disciplina: "Emergências Pediátricas", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "5", aula: "Classificação dos Estudos Epidemiológicos", professor: "Darizon José de Oliveira Filho", disciplina: "Epidemiologia", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "5", aula: "Associação x Causalidade", professor: "Darizon José de Oliveira Filho", disciplina: "Epidemiologia", grandeArea: "Preventiva", importancia: "Verde" },
    // Moved from Bloco 6 to Bloco 5 per user request
    { bloco: "5", aula: "Rastreamentos", professor: "Beatriz Neves Coelho", disciplina: "MFC", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "5", aula: "Trauma: Encerramento", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "5", aula: "Queimaduras", professor: "Rafael Pallerosi de Figueiredo", disciplina: "Cirurgia Plástica", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "5", aula: "Escroto Agudo", professor: "Matheus Tiseu Ruggeri", disciplina: "Urologia", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "5", aula: "Priapismo", professor: "Matheus Tiseu Ruggeri", disciplina: "Urologia", grandeArea: "Cirurgia", importancia: "Vermelho" },

    // Bloco 6
    { bloco: "6", aula: "Gasometria Arterial", professor: "Felipe Carvalho", disciplina: "Nefrologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "6", aula: "Distúrbios do Sódio", professor: "Felipe Carvalho", disciplina: "Nefrologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "6", aula: "Distúrbios do Potássio", professor: "Felipe Carvalho", disciplina: "Nefrologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "6", aula: "Reações Alérgicas", professor: "Alex Isidoro Ferreira Prado", disciplina: "Imunologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "6", aula: "Amenorreia Secundária", professor: "Nicole Kemberly Ribeiro Rocha", disciplina: "Ginecologia Endócrina", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "6", aula: "Hiperprolactinemia", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Endócrina", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "6", aula: "Síndrome dos Ovários Policísticos", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Endócrina", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "6", aula: "Infecções de Vias Aéreas Superiores", professor: "Roberta de Oliveira Andrade", disciplina: "Infectologia Pediátrica", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "6", aula: "Autoinflamatórias", professor: "Alex Isidoro Ferreira Prado", disciplina: "Esp. Ped: Imuno", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "6", aula: "Pneumonias", professor: "Giovanna Pereira Tardin", disciplina: "Infectologia Pediátrica", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "6", aula: "Bronquiolite e Coqueluche", professor: "Giovanna Pereira Tardin", disciplina: "Infectologia Pediátrica", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "6", aula: "COVID", professor: "Giovanna Pereira Tardin", disciplina: "Infectologia Pediátrica", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "6", aula: "Estudos Transversais", professor: "Darizon José de Oliveira Filho", disciplina: "Epidemiologia Clínica", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "6", aula: "Estudos Longitudinais", professor: "Darizon José de Oliveira Filho", disciplina: "Epidemiologia Clínica", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "6", aula: "Abdome Agudo: Introdução", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "6", aula: "Apendicite Aguda", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "6", aula: "Cicatrização e Lesões por Pressão", professor: "Rafael Pallerosi de Figueiredo", disciplina: "Cirurgia Plástica", grandeArea: "Cirurgia", importancia: "Amarelo" },
    { bloco: "6", aula: "Fios de Sutura", professor: "Rafael Pallerosi de Figueiredo", disciplina: "Cirurgia Plástica", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "6", aula: "Anestésicos Locais", professor: "Rafael Pallerosi de Figueiredo", disciplina: "Cirurgia Plástica", grandeArea: "Cirurgia", importancia: "Roxo" },

    // Bloco 7
    { bloco: "7", aula: "Antibióticos", professor: "Jaqueline Fabiano Palazzo", disciplina: "Infectologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "7", aula: "Anemias Hemolíticas", professor: "Marco Aurélio Campanha Sartori", disciplina: "Hematologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "7", aula: "Oncologia: emergências e paliativos", professor: "Lucas Lobo Mesquita", disciplina: "Oncologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "7", aula: "Infecções e Gravidez", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "7", aula: "Rotura Prematura de Membranas", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "7", aula: "Violência Sexual", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "7", aula: "Interrupção Legal da Gestação", professor: "Gelson Farias Arcos Júnior", disciplina: "Obstetrícia Básico", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "7", aula: "Reanimação Neonatal", professor: "Amira Kheireddine Saleh", disciplina: "Neonatologia", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "7", aula: "Infecções Congênitas", professor: "Amira Kheireddine Saleh", disciplina: "Neonatologia", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "7", aula: "Icterícia e Colestase Neonatal", professor: "Amira Kheireddine Saleh", disciplina: "Neonatologia", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "7", aula: "História e Princípios do SUS", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "7", aula: "Cardiologia na APS", professor: "Beatriz Neves Coelho", disciplina: "MFC", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "7", aula: "Urgências da Vesícula Biliar", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "7", aula: "Câncer de Esôfago", professor: "Felipe Alexandre Fernandes", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Verde" },

    // Bloco 8
    { bloco: "8", aula: "Cefaleias", professor: "Leonardo de Sousa Bernardes", disciplina: "Neurologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "8", aula: "Avaliação Geriátrica Ampla", professor: "Priscila Yumi Abiko", disciplina: "Geriatria", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "8", aula: "Grandes Síndromes Geriátricas", professor: "Priscila Yumi Abiko", disciplina: "Geriatria", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "8", aula: "Avaliação de enzimas hepáticas", professor: "Rafael Bandeira Lages", disciplina: "Gastroenterologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "8", aula: "Doenças hepáticas: CBP, CEP, HAI", professor: "Rafael Bandeira Lages", disciplina: "Gastroenterologia", grandeArea: "Clínica", importancia: "Roxo" },
    { bloco: "8", aula: "Abortamento", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "8", aula: "Gestação Ectópica", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "8", aula: "Doença Trofoblástica Gestacional", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "8", aula: "Dermatite Atópica", professor: "Laura Coimbra Teixeira", disciplina: "Esp. Ped: Dermato", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "8", aula: "Dermatoses e Infecções", professor: "Roberta de Oliveira Andrade", disciplina: "Esp. Ped: Dermato", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "8", aula: "Legislação do SUS I", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "8", aula: "Pancreatite Aguda", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "8", aula: "Diverticulite Aguda", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "8", aula: "Abscesso Hepático", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "8", aula: "Disfagia e Acalasia", professor: "Felipe Alexandre Fernandes", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Amarelo" },
    { bloco: "8", aula: "Hernias de Hiato", professor: "Felipe Alexandre Fernandes", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },

    // Bloco 9
    { bloco: "9", aula: "Coagulação e Hemostasia", professor: "Marco Aurélio Campanha Sartori", disciplina: "Hematologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "9", aula: "Hemoterapia", professor: "Marco Aurélio Campanha Sartori", disciplina: "Hematologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "9", aula: "Cirrose Hepática I", professor: "Rafael Bandeira Lages", disciplina: "Gastroenterologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "9", aula: "Cirrose Hepática II", professor: "Rafael Bandeira Lages", disciplina: "Gastroenterologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "9", aula: "Pneumonia Adquirida na Comunidade", professor: "Nathalia Zorze Rosseto", disciplina: "Pneumologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "9", aula: "Derrame Pleural", professor: "Nathalia Zorze Rosseto", disciplina: "Pneumologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "9", aula: "Placenta Prévia", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "9", aula: "Descolamento Prematuro de Placenta", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "9", aula: "Outros Sangramentos da Gestação", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "9", aula: "Anemia Falciforme", professor: "Julia Loureiro Sion", disciplina: "Esp. Ped: Hemato", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "9", aula: "Anemia Ferropriva e Talassemia", professor: "Julia Loureiro Sion", disciplina: "Esp. Ped: Hemato", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "9", aula: "Hemostasia e Distúrbios Hemorrágicos", professor: "Julia Loureiro Sion", disciplina: "Esp. Ped: Hemato", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "9", aula: "Genética", professor: "Roberta de Oliveira Andrade", disciplina: "Genética", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "9", aula: "Legislação do SUS II", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "9", aula: "Tabagismo", professor: "Beatriz Neves Coelho", disciplina: "MFC", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "9", aula: "Abdome Agudo Obstrutivo", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "9", aula: "Abdome Agudo Perfurativo e Vascular", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "9", aula: "Câncer de Estômago", professor: "Juan David Ruiz Perez", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Verde" },

    // Bloco 10
    { bloco: "10", aula: "HAS : Ambulatorial e Emergências", professor: "Julia Tormin", disciplina: "Cardiologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "10", aula: "Insuficiência Cardíaca", professor: "Julia Tormin", disciplina: "Cardiologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "10", aula: "Espirometria e Asma", professor: "Nathalia Zorze Rosseto", disciplina: "Pneumologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "10", aula: "DPOC", professor: "Nathalia Zorze Rosseto", disciplina: "Pneumologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "10", aula: "BLS e ACLS", professor: "Yago Padovan e Gelson Arcos", disciplina: "Emergências", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "10", aula: "Síndromes Hipertensivas na Gestação", professor: "Graciella Calsolari Figueiredo de Farias", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "10", aula: "Sangramento Uterino Anormal", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "10", aula: "PALS", professor: "Camilla Silva Castro e Sousa", disciplina: "Emergências Pediátricas", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "10", aula: "Cardiopatias Congênitas", professor: "Camilla Silva Castro e Sousa", disciplina: "Esp. Ped: Cardio", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "10", aula: "HAS (Pediatria)", professor: "Camilla Silva Castro e Sousa", disciplina: "Esp. Ped: Cardio", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "10", aula: "Miocardite, Síncope, IC", professor: "Camilla Silva Castro e Sousa", disciplina: "Esp. Ped: Cardio", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "10", aula: "Medidas de Associação", professor: "Darizon José de Oliveira Filho", disciplina: "Epidemiologia Clínica", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "10", aula: "Legislação do SUS 3", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "10", aula: "RAPS", professor: "Carlos Rafael Dantas", disciplina: "Psiquiatria", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "10", aula: "Anatomia da Parede Abdominal", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "10", aula: "Hernioplastia Inguinal", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Amarelo" },
    { bloco: "10", aula: "Outras Neoplasias Gástricas", professor: "Juan David Ruiz Perez", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "10", aula: "Enxertos e Retalhos", professor: "Juan David Ruiz Perez", disciplina: "Cirurgia Plástica", grandeArea: "Cirurgia", importancia: "Amarelo" },

    // Bloco 11
    { bloco: "11", aula: "Diabetes: Classificação", professor: "Mariana Ramos de Santana", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "11", aula: "Diabetes: Tratamento", professor: "Mariana Ramos de Santana", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "11", aula: "Emergências Hiperglicêmicas", professor: "Yago Henrique Padovan Chio", disciplina: "Emergências", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "11", aula: "Hiperglicemia Hospitalar", professor: "Mariana Ramos de Santana", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Roxo" },
    { bloco: "11", aula: "Diabetes na Gestação", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "11", aula: "Infertilidade", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Endócrina", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "11", aula: "Endometriose", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "11", aula: "Arboviroses (Ped)", professor: "Giovanna Pereira Tardin", disciplina: "Infectologia Pediátrica", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "11", aula: "Doenças Exantemáticas", professor: "Giovanna Pereira Tardin", disciplina: "Infectologia Pediátrica", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "11", aula: "Cetoacidose Diabética (Ped)", professor: "Roberta de Oliveira Andrade", disciplina: "Esp. Ped: Endocrino", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "11", aula: "Financiamento do SUS", professor: "Gustavo Antônio Toniatti", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "11", aula: "Ensaios Clínicos", professor: "Darizon José de Oliveira Filho", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "11", aula: "Ética em Pesquisa Clínica", professor: "Darizon José de Oliveira Filho", disciplina: "Epidemiologia Clínica", grandeArea: "Preventiva", importancia: "Amarelo" },
    { bloco: "11", aula: "Síndrome Compartimental Intra-Abdominal", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Amarelo" },
    { bloco: "11", aula: "Hérnias Incisionais", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "11", aula: "Outras Hérnias", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "11", aula: "Urgências endoscópicas", professor: "Pier Paolo Paradisi", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" }, 
    // Bloco 12

    { bloco: "12", aula: "Síndrome Metabólica e Obesidade", professor: "Mariana Ramos de Santana", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "12", aula: "Dislipidemias", professor: "Felipe Johansen Capri", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "12", aula: "Doença Hepática Esteatótica", professor: "Rafael Bandeira Lages", disciplina: "Gastroenterologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "12", aula: "Propedêutica em Uroginecologia", professor: "Juliana Ribeiro da Silva", disciplina: "Uroginecologia", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "12", aula: "Incontinência Urinária", professor: "Juliana Ribeiro da Silva", disciplina: "Uroginecologia", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "12", aula: "Prolapso Genital", professor: "Juliana Ribeiro da Silva", disciplina: "Uroginecologia", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "12", aula: "Triagens Neonatais", professor: "Amira Kheireddine Saleh", disciplina: "Neonatologia", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "12", aula: "Distúrbios Metabólicos Neonatais", professor: "Amira Kheireddine Saleh", disciplina: "Neonatologia", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "12", aula: "Peçonhentos, Raiva e Tétano", professor: "Laura Coimbra Teixeira", disciplina: "Emergências Pediátricas", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "12", aula: "Ingestão e Aspiração de Corpo Estranho", professor: "Laura Coimbra Teixeira", disciplina: "Emergências Pediátricas", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "12", aula: "Preventiva: a Jornada Continua", professor: "Darizon José de Oliveira Filho", disciplina: "Preventiva", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "12", aula: "Significância Estatística", professor: "Darizon José de Oliveira Filho", disciplina: "Epidemiologia Clínica", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "12", aula: "Revisão Sistemática e Metanálise", professor: "Darizon José de Oliveira Filho", disciplina: "Epidemiologia Clínica", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "12", aula: "MBE", professor: "Darizon José de Oliveira Filho", disciplina: "Epidemiologia Clínica", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "12", aula: "Pré-Operatório", professor: "Pier Paolo Paradisi", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "12", aula: "Uro-Oncologia", professor: "Augusto Quaresma Coelho", disciplina: "Urologia", grandeArea: "Cirurgia", importancia: "Amarelo" },
    { bloco: "12", aula: "Cirurgia Bariátrica", professor: "Felipe Alexandre Fernandes", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Verde" },

    // Bloco 13
    { bloco: "13", aula: "Vasculites", professor: "Henrique Helson Herter Dalmolin", disciplina: "Reumatologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "13", aula: "Tuberculose: clínica e diagnóstico", professor: "Jaqueline Fabiano Palazzo", disciplina: "Infectologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "13", aula: "Tuberculose: tratamento", professor: "Jaqueline Fabiano Palazzo", disciplina: "Infectologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "13", aula: "Avaliação de Vitalidade Fetal", professor: "Gelson Farias Arcos Júnior", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "13", aula: "Restrição de Crescimento Intrauterino", professor: "Gelson Farias Arcos Júnior", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "13", aula: "Sofrimento Fetal Crônico", professor: "Gelson Farias Arcos Júnior", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "13", aula: "Gemelaridade", professor: "Gelson Farias Arcos Júnior", disciplina: "Medicina fetal", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "13", aula: "Convulsão na Emergência", professor: "Joemir Jabson da Conceição Brito", disciplina: "Neuro Ped", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "13", aula: "Tuberculose (Ped)", professor: "Giovanna Pereira Tardin", disciplina: "Infectologia Pediátrica", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "13", aula: "Pediatria Geral", professor: "Amira Kheireddine Saleh", disciplina: "Puericultura", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "13", aula: "Diabetes no SUS", professor: "Beatriz Neves Coelho", disciplina: "MFC", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "13", aula: "Estratégia da Saúde da Família", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "13", aula: "REMIT e pós-operatório", professor: "Pier Paolo Paradisi", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "13", aula: "Perioperatório: Complicações", professor: "Pier Paolo Paradisi", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "13", aula: "Fraturas de face", professor: "Rafael Pallerosi de Figueiredo", disciplina: "Cirurgia Plástica", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "13", aula: "Paralisia facial", professor: "Rafael Pallerosi de Figueiredo", disciplina: "Cirurgia Plástica", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "13", aula: "Hiperplasia prostática benigna", professor: "Matheus Tiseu Ruggeri", disciplina: "Urologia", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "13", aula: "Cirurgia Geral: Respiro", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Verde" },

    // Bloco 14
    { bloco: "14", aula: "Meningites & Encefalites", professor: "Leonardo de Sousa Bernardes", disciplina: "Neurologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "14", aula: "Doenças Neuromusculares e Parkinson", professor: "Leonardo de Sousa Bernardes", disciplina: "Neurologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "14", aula: "Taquiarritmias", professor: "Julia Pereira Afonso dos Santos Tormin", disciplina: "Cardiologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "14", aula: "Bradiarritimias", professor: "Julia Pereira Afonso dos Santos Tormin", disciplina: "Cardiologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "14", aula: "Síncope", professor: "Julia Pereira Afonso dos Santos Tormin", disciplina: "Cardiologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "14", aula: "Doenças Valvares", professor: "Julia Pereira Afonso dos Santos Tormin", disciplina: "Cardiologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "14", aula: "Cardiopatias na Gravidez", professor: "Graciella Calsolari Figueiredo de Farias", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Vermelho" },
    { bloco: "14", aula: "Anticoncepção", professor: "Nicole Kemberly Ribeiro Rocha", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "14", aula: "Kawasaki, Vasculite por Iga", professor: "Laura Coimbra Teixeira", disciplina: "Esp. Ped: Reumato", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "14", aula: "Artrite Idiopática Juvenil", professor: "Henrique Helson Herter Dalmolin", disciplina: "Esp. Ped: Reumato", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "14", aula: "Meningite e Encefalite (Ped)", professor: "Giovanna Pereira Tardin", disciplina: "Infectologia Pediátrica", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "14", aula: "Financiamento da APS", professor: "Gustavo Antônio Toniatti", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "14", aula: "Síndrome Depressiva", professor: "Carlos Rafael Dantas", disciplina: "Psiquiatria", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "14", aula: "Síndrome Maníaca", professor: "Carlos Rafael Dantas", disciplina: "Psiquiatria", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "14", aula: "Câncer colorretal", professor: "Felipe Alexandre Fernandes", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "14", aula: "Doenças Orificiais", professor: "Felipe Alexandre Fernandes", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "14", aula: "Doenças da Vesícula Biliar", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },

    // Bloco 15

    { bloco: "15", aula: "Via aérea, intubação e VNI", professor: "Yago Henrique Padovan Chio", disciplina: "Emergências", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "15", aula: "SDRA", professor: "Douglas Toledo Camilo", disciplina: "UTI", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "15", aula: "Ventilação Mecânica", professor: "Douglas Toledo Camilo", disciplina: "UTI", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "15", aula: "Infecções Nosocomiais", professor: "Douglas Toledo Camilo", disciplina: "UTI", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "15", aula: "Choque", professor: "Douglas Toledo Camilo", disciplina: "UTI", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "15", aula: "Drogas Vasoativas", professor: "Douglas Toledo Camilo", disciplina: "UTI", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "15", aula: "Vacinação (Adulto)", professor: "Caio Trevellin Sambo", disciplina: "Hematologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "15", aula: "Propedêutica Mamária", professor: "Maria Silveira Carvalho Alves", disciplina: "Mastologia", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "15", aula: "Principais Sintomas em Mastologia", professor: "Maria Silveira Carvalho Alves", disciplina: "Mastologia", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "15", aula: "Classificação das Lesões Benignas", professor: "Maria Silveira Carvalho Alves", disciplina: "Mastologia", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "15", aula: "Vacinação (Ped)", professor: "Giovanna Pereira Tardin", disciplina: "Infectologia Pediátrica", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "15", aula: "HIV (Ped)", professor: "Giovanna Pereira Tardin", disciplina: "Infectologia Pediátrica", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "15", aula: "Ortopedia Pediátrica", professor: "Hugo Henrique Moreira", disciplina: "Esp. Ped: Ortopedia", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "15", aula: "Osteomielite e Artrite Séptica", professor: "Hugo Henrique Moreira", disciplina: "Esp. Ped: Ortopedia", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "15", aula: "Ferramentas da APS/ESF", professor: "Carlos Rafael Dantas", disciplina: "MFC", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "15", aula: "Síndrome Ansiosa", professor: "Carlos Rafael Dantas", disciplina: "Psiquiatria", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "15", aula: "Fígado para perdidos", professor: "Matheus Ettinger Mendes", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "15", aula: "Nódulos hepáticos benignos", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "15", aula: "Ferimento descolante", professor: "Rafael Pallerosi de Figueiredo", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Vermelho" },

    // Bloco 16
    { bloco: "16", aula: "Injúria Renal", professor: "Felipe Carvalho", disciplina: "Nefrologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "16", aula: "Diarreia Agudas e Colite", professor: "Rafael Bandeira Lages", disciplina: "Gastroenterologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "16", aula: "Diarreias Crônicas", professor: "Rafael Bandeira Lages", disciplina: "Gastroenterologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "16", aula: "Doença Inflamatória Intestinal", professor: "Rafael Bandeira Lages", disciplina: "Gastroenterologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "16", aula: "Doenças Negligenciadas", professor: "Caio Trevellin Sambo", disciplina: "Infectologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "16", aula: "Trabalho de Parto Prematuro", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "16", aula: "Colo Curto", professor: "Graciella Calsolari Figueiredo de Farias", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "16", aula: "Hiperplasia Adrenal Congênita", professor: "Roberta de Oliveira Andrade", disciplina: "Esp. Ped: Endocrino", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "16", aula: "Hipotireoidismo", professor: "Roberta de Oliveira Andrade", disciplina: "Esp. Ped: Endocrino", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "16", aula: "Diferenças no Desenvolvimento Sexual", professor: "Roberta de Oliveira Andrade", disciplina: "Esp. Ped: Endocrino", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "16", aula: "Nutrologia em Pediatria", professor: "Marília Isabela Silveira de Morais", disciplina: "Esp. Ped: Nutrologia", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "16", aula: "Telessaúde", professor: "Beatriz Neves Coelho", disciplina: "MFC", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "16", aula: "Método Clínico Centrado na Pessoa", professor: "Carlos Rafael Dantas", disciplina: "MFC", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "16", aula: "Litíase Renal", professor: "Matheus Tiseu Ruggeri", disciplina: "Urologia", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "16", aula: "Carcinoma hepatocelular", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "16", aula: "Aneurisma de aorta", professor: "Tayrine Mazotti de Moraes", disciplina: "Cirurgia Vascular", grandeArea: "Cirurgia", importancia: "Amarelo" },

    // Bloco 17
    { bloco: "17", aula: "Lúpus Eritematoso Sistêmico", professor: "Henrique Helson Herter Dalmolin", disciplina: "Reumatologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "17", aula: "Osteoporose", professor: "Henrique Helson Herter Dalmolin", disciplina: "Reumatologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "17", aula: "Esclerose Sistêmica", professor: "Henrique Helson Herter Dalmolin", disciplina: "Reumatologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "17", aula: "Doença de Sjögren", professor: "Henrique Helson Herter Dalmolin", disciplina: "Reumatologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "17", aula: "Miopatias Autoimunes", professor: "Henrique Helson Herter Dalmolin", disciplina: "Reumatologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "17", aula: "Glomerulopatias", professor: "Felipe Carvalho", disciplina: "Nefrologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "17", aula: "Intoxicações Exógenas", professor: "Yago Henrique Padovan Chio", disciplina: "Emergências", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "17", aula: "Hemorragia pós parto", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "17", aula: "Puerpério", professor: "Graciella Calsolari Figueiredo de Farias", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "17", aula: "Asma", professor: "Camilla Silva Castro e Sousa", disciplina: "Esp. Ped: Pneumo", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "17", aula: "Fibrose Cística", professor: "Camilla Silva Castro e Sousa", disciplina: "Esp. Ped: Pneumo", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "17", aula: "Imunodeficiências", professor: "Alex Isidoro Ferreira Prado", disciplina: "Esp. Ped: Imuno", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "17", aula: "Vigilância em Saúde", professor: "Luana Alves Suleiman", disciplina: "Epidemiologia", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "17", aula: "Registro de Saúde (ReSOAP)", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Amarelo" },
    { bloco: "17", aula: "Metástases hepáticas", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "17", aula: "Adenocarcinoma de pâncreas", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "17", aula: "Fígado e VB: Quiz", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },
    // Bloco 18

    { bloco: "18", aula: "HIV e Doenças Oportunistas", professor: "Jaqueline Fabiano Palazzo", disciplina: "Infectologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "18", aula: "Fisiologia da Tireoide", professor: "Mariana Ramos de Santana", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "18", aula: "Hipertireoidismo", professor: "Mariana Ramos de Santana", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "18", aula: "Epilepsia", professor: "Leonardo de Sousa Bernardes", disciplina: "Neurologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "18", aula: "Esclerose Múltipla", professor: "Leonardo de Sousa Bernardes", disciplina: "Neurologia", grandeArea: "Clínica", importancia: "Roxo" },
    { bloco: "18", aula: "Câncer de Colo de Útero - Rastreamento", professor: "Marilia Albanezi Bertolazzi", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "18", aula: "Câncer de Colo de Útero - Diagnóstico", professor: "Marilia Albanezi Bertolazzi", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "18", aula: "Doenças da Vulva", professor: "Marilia Albanezi Bertolazzi", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Vermelho" },
    { bloco: "18", aula: "Sepse Neonatal", professor: "Amira Kheireddine Saleh", disciplina: "Neonatologia", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "18", aula: "Desconforto Respiratório Neonatal", professor: "Amira Kheireddine Saleh", disciplina: "Neonatologia", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "18", aula: "Outras Doenças Neonatais", professor: "Amira Kheireddine Saleh", disciplina: "Neonatologia", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "18", aula: "Nutrição do Pré-Termo", professor: "Amira Kheireddine Saleh", disciplina: "Neonatologia", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "18", aula: "Processo Epidêmico", professor: "Luana Alves Suleiman", disciplina: "Epidemiologia", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "18", aula: "Abordagem Familiar", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Amarelo" },
    { bloco: "18", aula: "Síndrome de Fournier", professor: "Pier Paolo Paradisi", disciplina: "Urologia", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "18", aula: "Ortopedia", professor: "Hugo Henrique Moreira", disciplina: "Ortopedia", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "18", aula: "Trombose venosa profunda", professor: "Tayrine Mazotti de Moraes", disciplina: "Cirurgia Vascular", grandeArea: "Cirurgia", importancia: "Amarelo" },
    { bloco: "18", aula: "Cirurgia Torácica: Pneumotórax", professor: "Eserval Rocha Junior", disciplina: "Cirurgia Torácica", grandeArea: "Cirurgia", importancia: "Roxo" },

    // Bloco 19

    { bloco: "19", aula: "Tromboembolismo Pulmonar", professor: "Nathalia Zorze Rosseto", disciplina: "Pneumologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "19", aula: "Distúrbios do Sono", professor: "Nathalia Zorze Rosseto", disciplina: "Pneumologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "19", aula: "Doença Pulmonar Intersticial", professor: "Nathalia Zorze Rosseto", disciplina: "Pneumologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "19", aula: "Nódulo Pulmonar", professor: "Nathalia Zorze Rosseto", disciplina: "Pneumologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "19", aula: "Adrenal", professor: "Felipe Johansen Capri", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "19", aula: "Síndrome de Cushing", professor: "Felipe Johansen Capri", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "19", aula: "Disfagia e Esofagite", professor: "Rafael Bandeira Lages", disciplina: "Gastroenterologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "19", aula: "Câncer de Mama - Rastreamento", professor: "Maria Silveira Carvalho Alves", disciplina: "Mastologia", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "19", aula: "Câncer de Mama - Fatores de Risco", professor: "Maria Silveira Carvalho Alves", disciplina: "Mastologia", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "19", aula: "Câncer de Mama - Doença Invasiva", professor: "Maria Silveira Carvalho Alves", disciplina: "Mastologia", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "19", aula: "Parasitoses Intestinais", professor: "Giovanna Pereira Tardin", disciplina: "Infectologia Pediátrica", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "19", aula: "Neoplasias Pediátricas", professor: "Julia Loureiro Sion", disciplina: "Oncologia Pediátrica", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "19", aula: "Acidente de Trabalho", professor: "Yuri Franco Trunckle", disciplina: "Medicina do Trabalho", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "19", aula: "Síndrome Psicótica", professor: "Carlos Rafael Dantas", disciplina: "Psiquiatria", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "19", aula: "Psicofarmacologia", professor: "Carlos Rafael Dantas", disciplina: "Psiquiatria", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "19", aula: "Oncocirurgia Geral", professor: "Pier Paolo Paradisi", disciplina: "Oncologia", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "19", aula: "Isquemia de membros inferiores", professor: "Tayrine Mazotti de Moraes", disciplina: "Cirurgia Vascular", grandeArea: "Cirurgia", importancia: "Amarelo" },

    // Bloco 20
    { bloco: "20", aula: "Infecção do Trato Urinário (ITU)", professor: "Felipe Carvalho", disciplina: "Nefrologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "20", aula: "Outro Distúrbios Hidroeletrolóiticos", professor: "Felipe Carvalho", disciplina: "Nefrologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "20", aula: "Doença Renal Crônica", professor: "Felipe Carvalho", disciplina: "Nefrologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "20", aula: "Síndrome Climatérica", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Endócrina", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "20", aula: "Terapia Hormonal", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Endócrina", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "20", aula: "Tumores Anexiais", professor: "Marilia Albanezi Bertolazzi", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "20", aula: "Câncer de Ovário", professor: "Marilia Albanezi Bertolazzi", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "20", aula: "Infecção de Trato Urinário (Ped)", professor: "Giovanna Pereira Tardin", disciplina: "Esp. Ped: Nefrologia", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "20", aula: "Sedoanalgesia", professor: "Thais Renata Hollanders dos Santos Fiani", disciplina: "Emergências Pediátricas", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "20", aula: "Sepse Pediátrica", professor: "Thais Renata Hollanders dos Santos Fiani", disciplina: "Emergências Pediátricas", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "20", aula: "Choque e Drogas Vasoativas", professor: "Thais Renata Hollanders dos Santos Fiani", disciplina: "Emergências Pediátricas", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "20", aula: "Pneumoconioses", professor: "Yuri Franco Trunckle", disciplina: "Medicina do Trabalho", grandeArea: "Preventiva", importancia: "Amarelo" },
    { bloco: "20", aula: "Tuberculose e Hanseníase na APS", professor: "Nathália Machado Cardoso", disciplina: "MFC", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "20", aula: "Saúde Socioecológica", professor: "Carlos Rafael Dantas", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Vermelho" },
    { bloco: "20", aula: "Cirurgia: Resumão", professor: "Henrique Simonsen Lunardeli", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Azul" },
    { bloco: "20", aula: "Neoplasias Císticas Pancreáticas", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "20", aula: "Pancreatite Crônica", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "20", aula: "Trauma Vascular", professor: "Tayrine Mazotti de Moraes", disciplina: "Cirurgia Vascular", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "20", aula: "Estenose Carotídea", professor: "Tayrine Mazotti de Moraes", disciplina: "Cirurgia Vascular", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "20", aula: "Cancer de Pulmão", professor: "Eserval Rocha Junior", disciplina: "Cirurgia Torácica", grandeArea: "Cirurgia", importancia: "Vermelho" },

    // Bloco 21

    { bloco: "21", aula: "Depressão e Delirium no Idoso", professor: "Priscila Yumi Abiko", disciplina: "Geriatria", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "21", aula: "Insuficiência Cognitiva", professor: "Priscila Yumi Abiko", disciplina: "Geriatria", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "21", aula: "Hiperplasia Endometrial", professor: "Marilia Albanezi Bertolazzi", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "21", aula: "Câncer de Endométrio", professor: "Marilia Albanezi Bertolazzi", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "21", aula: "Outras Intercorrências Clínicas", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "21", aula: "Cirurgia Pediátrica no PS", professor: "Victor da Paixão Guimarães", disciplina: "Esp. Ped: Cirurgia", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "21", aula: "Uropediatria e Hérnias", professor: "Victor da Paixão Guimarães", disciplina: "Esp. Ped: Urologia", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "21", aula: "Malformações Congênitas", professor: "Victor da Paixão Guimarães", disciplina: "Esp. Ped: Cirurgia", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "21", aula: "Declaração de Óbito", professor: "Yuri Franco Trunckle", disciplina: "Medicina Legal", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "21", aula: "Atenção à Saúde de Populações", professor: "Felipe Daiko Fraga", disciplina: "MFC", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "21", aula: "Videolaparoscopia", professor: "Pier Paolo Paradisi", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "21", aula: "Eletrocirurgia", professor: "Pier Paolo Paradisi", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "21", aula: "Pâncreas e vias biliares", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "21", aula: "Nutrição perioperatória", professor: "Carlos de Almeida Obregon", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "21", aula: "Diagnósticos diferenciais massas cervicais", professor: "Felipe Ferraz Magnabosco", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "21", aula: "Insuficiência venosa crônica", professor: "Tayrine Mazotti de Moraes", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "21", aula: "Cirurgia Vascular: Síndromes Compressivas", professor: "Tayrine Mazotti de Moraes", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Vermelho" },

    // Bloco 22
    { bloco: "22", aula: "Doenças Virais e Pandêmicas", professor: "Caio Trevellin Sambo", disciplina: "Infectologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "22", aula: "Arboviroses", professor: "Jaqueline Palazzo", disciplina: "Infectologia", grandeArea: "Clínica", importancia: "Azul" },
    { bloco: "22", aula: "Icterícias febris", professor: "Jaqueline Fabiano Palazzo", disciplina: "Infectologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "22", aula: "Hepatites Virais", professor: "Jaqueline Fabiano Palazzo", disciplina: "Hematologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "22", aula: "Técnicas de Reprodução Assistida", professor: "Amanda Lino de Faria Lessa", disciplina: "Ginecologia Endócrina", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "22", aula: "Cuidado à Saúde LGBTQIAPN+", professor: "Gelson Farias Arcos Júnior", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "22", aula: "Medicina do Adolescente", professor: "Laura Coimbra Teixeira", disciplina: "Esp. Ped: Adolescência", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "22", aula: "Ética em Pediatria", professor: "Marília Isabela Silveira de Morais", disciplina: "Esp. Ped: Adolescência", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "22", aula: "Ética Médica", professor: "Yuri Franco Trunckle", disciplina: "Medicina Legal", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "22", aula: "Intoxicações", professor: "Yuri Franco Trunckle", disciplina: "Medicina do Trabalho", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "22", aula: "Dermatologia na APS", professor: "Nathália Machado Cardoso", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "22", aula: "Tumores do Intestino Delgado", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "22", aula: "Doenças cirúrgicas do Baço", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "22", aula: "CEC de Cabeça e Pescoço", professor: "Felipe Ferraz Magnabosco", disciplina: "Cirurgia de Cabeça e Pescoço", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "22", aula: "Doenças Traqueais", professor: "Eserval Rocha Junior", disciplina: "Cirurgia Torácica", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "22", aula: "Bronquiectasias e hemoptise", professor: "Eserval Rocha Junior", disciplina: "Cirurgia Torácica", grandeArea: "Cirurgia", importancia: "Vermelho" },

    // Bloco 23

    { bloco: "23", aula: "Hiperaldosteronismo Primário", professor: "Felipe Johansen Capri", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "23", aula: "Feocromocitoma", professor: "Felipe Johansen Capri", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "23", aula: "Prolactinomas", professor: "Felipe Johansen Capri", disciplina: "Endocrinologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "23", aula: "Oncohematologia", professor: "Marco Aurélio Campanha Sartori", disciplina: "Oncologia", grandeArea: "Clínica", importancia: "Vermelho" },
    { bloco: "23", aula: "Cirurgia Ginecológica", professor: "Marilia Albanezi Bertolazzi", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Verde" },
    { bloco: "23", aula: "Transtornos Psiquiátricos na Gestação", professor: "Graciella Calsolari Figueiredo de Farias", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "23", aula: "Emergências Psiquiátricas", professor: "Carlos Rafael Dantas", disciplina: "Psiquiatria", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "23", aula: "Violências e Vulnerabilidade", professor: "Felipe Daiko Fraga", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Azul" },
    { bloco: "23", aula: "Saúde Privada", professor: "Gustavo Antônio Toniatti", disciplina: "Saúde Coletiva", grandeArea: "Preventiva", importancia: "Amarelo" },
    { bloco: "23", aula: "Psiquiatria da Infância", professor: "Carlos Rafael Dantas", disciplina: "Esp. Ped: Psiquiatria", grandeArea: "Pediatria", importancia: "Amarelo" },
    { bloco: "23", aula: "Epilepsias na Infância", professor: "Joemir Jabson da Conceição Brito", disciplina: "Esp. Ped: Neurologia", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "23", aula: "Cisto pilonidal", professor: "Carlos de Almeida Obregon", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "23", aula: "Anomalias Congênitas em cabeça", professor: "Felipe Ferraz Magnabosco", disciplina: "Cirurgia de Cabeça e Pescoço", grandeArea: "Cirurgia", importancia: "Amarelo" },
    { bloco: "23", aula: "Mediastino", professor: "Eserval Rocha Junior", disciplina: "Cirurgia Torácica", grandeArea: "Cirurgia", importancia: "Vermelho" },

    // Bloco 24

    { bloco: "24", aula: "Dermatologia", professor: "Stella Meireles e Elisa Coelho", disciplina: "Dermatologia", grandeArea: "Clínica", importancia: "Verde" },
    { bloco: "24", aula: "Medicina Fetal", professor: "Gelson Farias Arcos Júnior", disciplina: "Medicina fetal", grandeArea: "G.O.", importancia: "Amarelo" },
    { bloco: "24", aula: "Otites, Perda Auditiva", professor: "Guilherme Rodrigues Marinho", disciplina: "Esp. Ped: Otorrino", grandeArea: "Pediatria", importancia: "Azul" },
    { bloco: "24", aula: "Rinites e Afecções", professor: "Guilherme Rodrigues Marinho", disciplina: "Esp. Ped: Otorrino", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "24", aula: "Transtornos alimentares", professor: "Carlos Rafael Dantas", disciplina: "Psiquiatria", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "24", aula: "Endoscopia", professor: "Luiza Bicudo", disciplina: "Cir. Ap. Digestivo", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "24", aula: "Cabeça e Pescoço: Tireóide", professor: "Felipe Ferraz Magnabosco", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "24", aula: "Cabeça e Pescoço: Paratireóide", professor: "Felipe Ferraz Magnabosco", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Vermelho" },
    { bloco: "24", aula: "Neurocirurgia", professor: "Ronaldo Dornelas de Faria Júnior", disciplina: "Cirurgia Geral", grandeArea: "Cirurgia", importancia: "Roxo" },

    // Bloco 25

    { bloco: "25", aula: "Anestesiologia", professor: "Luan Cayke Marinho de Oliveira", disciplina: "Anestesiologia", grandeArea: "Cirurgia", importancia: "Roxo" },
    { bloco: "25", aula: "Saúde do Trabalhador", professor: "Yuri Franco Trunckle", disciplina: "Medicina do Trabalho", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "25", aula: "Oftalmopediatria", professor: "Carolina Minelli Martines", disciplina: "Esp. Ped: Oftalmologia", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "25", aula: "Doença Hemolítica Perinatal", professor: "Gelson Farias Arcos Júnior", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Azul" },
    { bloco: "25", aula: "Trombofilias na Gestação", professor: "Isabela Marangon Pasotti", disciplina: "Obstetrícia Alto Risco", grandeArea: "G.O.", importancia: "Vermelho" },
    { bloco: "25", aula: "Oftalmologia para o Generalista I", professor: "Carolina Minelli Martines", disciplina: "Oftalmologia", grandeArea: "Cirurgia", importancia: "Amarelo" },
    { bloco: "25", aula: "Otologia II", professor: "Guilherme Rodrigues Marinho", disciplina: "Otorrinolaringologia", grandeArea: "Cirurgia", importancia: "Amarelo" },
    { bloco: "25", aula: "Otologia I", professor: "Guilherme Rodrigues Marinho", disciplina: "Otorrinolaringologia", grandeArea: "Cirurgia", importancia: "Amarelo" },

    // Bloco 26
    { bloco: "26", aula: "Rinologia", professor: "Guilherme Rodrigues Marinho", disciplina: "Otorrinolaringologia", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "26", aula: "Bucofaringolaringologia I", professor: "Guilherme Rodrigues Marinho", disciplina: "Otorrinolaringologia", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "26", aula: "Bucofaringolaringologia II", professor: "Guilherme Rodrigues Marinho", disciplina: "Otorrinolaringologia", grandeArea: "Cirurgia", importancia: "Verde" },
    { bloco: "26", aula: "Oftamologia para o Generalista II", professor: "Carolina Minelli Martines", disciplina: "Oftalmologia", grandeArea: "Cirurgia", importancia: "Amarelo" },
    { bloco: "26", aula: "Outras Urgências Ginecológicas", professor: "Nicole Kemberly Ribeiro Rocha", disciplina: "Ginecologia Geral", grandeArea: "G.O.", importancia: "Vermelho" },
    { bloco: "26", aula: "Malformações do Sistema Nervoso", professor: "José Marcos Vieira de Albuquerque Filho", disciplina: "Esp. Ped: Neurologia", grandeArea: "Pediatria", importancia: "Verde" },
    { bloco: "26", aula: "Doenças Neuromusculares na Infância", professor: "José Marcos Vieira de Albuquerque Filho", disciplina: "Esp. Ped: Neurologia", grandeArea: "Pediatria", importancia: "Vermelho" },
    { bloco: "26", aula: "Transtornos Relacionados a Substâncias", professor: "Carlos Rafael Dantas", disciplina: "Psiquiatria", grandeArea: "Clínica", importancia: "Amarelo" },
    { bloco: "26", aula: "Preventiva: reta final", professor: "Darizon José de Oliveira Filho", disciplina: "Preventiva", grandeArea: "Preventiva", importancia: "Verde" },
    { bloco: "26", aula: "Cirurgia Cardíaca", professor: "Matheus Gastaldo", disciplina: "Cirurgia Cardíaca", grandeArea: "Cirurgia", importancia: "Roxo" }
];

export const MEDCOF_SCHEDULE: ScheduleItem[] = RAW_DATA.map(item => ({
    id: generateId(item),
    bloco: item.bloco,
    grandeArea: item.grandeArea,
    disciplina: item.disciplina,
    aula: item.aula,
    professor: item.professor,
    importancia: item.importancia
}));
