
import { ScheduleItem } from '../types';

// Helper to map Discipline to Grand Area
const mapGrandeArea = (disciplina: string): string => {
    const d = disciplina.toLowerCase();
    if (d.includes('cirurgia') || d.includes('trauma') || d.includes('ortopedia') || d.includes('oftalmo') || d.includes('otorrino') || d.includes('urologia')) return 'Cirurgia';
    if (d.includes('pediatria') || d.includes('neonatologia') || d.includes('puericultura')) return 'Pediatria';
    if (d.includes('ginecologia') || d.includes('obstetrícia') || d.includes('mastologia')) return 'Ginecologia e Obstetrícia';
    if (d.includes('preventiva') || d.includes('sus') || d.includes('epidemiologia') || d.includes('medicina de família') || d.includes('medicina legal')) return 'Preventiva';
    return 'Clínica Médica'; // Default catch-all (Cardio, Pneumo, Gastro, etc)
};

const generateId = (week: string, subject: string, topic: string) => {
    return `em25-${week}-${subject}-${topic}`.replace(/\s+/g, '-').toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
};

const RAW_DATA = [
    { s: "1", d: "Pediatria", a: "Imunizações" },
    { s: "1", d: "Cirurgia", a: "Trauma - Avaliação Inicial, Vias Aéreas e Trauma Torácico" },
    { s: "1", d: "Preventiva", a: "História do SUS" },
    { s: "1", d: "Ginecologia", a: "Anatomia e Embriologia do Trato Genital Feminino" },
    { s: "1", d: "Obstetrícia", a: "Modificações Fisiológicas da Gestação" },
    { s: "1", d: "Cardiologia", a: "Hipertensão Arterial Sistêmica (Parte 1): Diagnóstico, Classificação, Avaliação" },
    
    { s: "2", d: "Pediatria", a: "Aleitamento Materno" },
    { s: "2", d: "Cirurgia", a: "Trauma - Choque" },
    { s: "2", d: "Ginecologia", a: "Ciclo Menstrual" },
    { s: "2", d: "Infectologia", a: "Antibióticos" },
    { s: "2", d: "Endocrino", a: "Introdução ao Diabetes Mellitus" },
    { s: "2", d: "Gastro", a: "Disfagia, Alterações Estruturais e Distúrbios da Motilidade do Esôfago" },

    { s: "3", d: "Pediatria", a: "Crescimento" },
    { s: "3", d: "Cirurgia", a: "Trauma Abdominal e Pélvico" },
    { s: "3", d: "Preventiva", a: "Princípios e Diretrizes do SUS" },
    { s: "3", d: "Obstetrícia", a: "Pré-Natal" },
    { s: "3", d: "Cardiologia", a: "Hipertensão Arterial Sistêmica (Parte 2): Tratamento" },
    { s: "3", d: "Nefrologia", a: "Doença Renal Crônica (DRC) - Parte I" },

    { s: "4", d: "Pediatria", a: "Puberdade" },
    { s: "4", d: "Cirurgia", a: "Trauma Populações Especiais (Pediátrico, Gestante e Idosos)" },
    { s: "4", d: "Ginecologia", a: "Miomatose Uterina" },
    { s: "4", d: "Infectologia", a: "Tuberculose" },
    { s: "4", d: "Endocrino", a: "Diabetes Mellitus Tipo 2" },
    { s: "4", d: "Neuro", a: "Anatomia, Fisiologia e Semiologia Neurológica" },

    { s: "5", d: "Pediatria", a: "Diagnóstico Nutricional" },
    { s: "5", d: "Cirurgia", a: "Trauma de Face e Cervical" },
    { s: "5", d: "Preventiva", a: "Marcos legais do Sistema Único de Saúde" },
    { s: "5", d: "Obstetrícia", a: "Bacia Obstétrica, Pelvimetria e Estática Fetal" },
    { s: "5", d: "Cardiologia", a: "Hipertensão Arterial Sistêmica (Parte 3): Secundária e Crise Hipertensiva" },
    { s: "5", d: "Pneumo", a: "Introdução a Pneumologia" },

    { s: "6", d: "Pediatria", a: "Desenvolvimento Neuropsicomotor" },
    { s: "6", d: "Cirurgia", a: "Trauma Vascular de Extremidades e Musculoesquelético" },
    { s: "6", d: "Ginecologia", a: "Adenomiose" },
    { s: "6", d: "Infectologia", a: "Leptospirose" },
    { s: "6", d: "Endocrino", a: "Diabetes Mellitus - Insulinoterapia e Cirurgia Metabólica" },
    { s: "6", d: "Gastro", a: "Doença do Refluxo Gastroesofágico, Esofagites Não-Pépticas e Ingestão de Corpo Estranho" },

    { s: "7", d: "Pediatria", a: "Deficiências Vitamínicas e Profilaxias" },
    { s: "7", d: "Cirurgia", a: "Queimaduras e Trauma Elétrico" },
    { s: "7", d: "Preventiva", a: "Financiamento em Saúde" },
    { s: "7", d: "Ginecologia", a: "Endometriose" },
    { s: "7", d: "Obstetrícia", a: "Mecanismo de Parto e Fases Clínicas do Parto" },
    { s: "7", d: "Cardiologia", a: "Insuficiência Cardíaca (Parte 1): Classificação, Fisiopatologia, Diagnóstico" },

    { s: "8", d: "Pediatria", a: "Cuidados Neonatais" },
    { s: "8", d: "Cirurgia", a: "Urgências Abdominais - Abdome Agudo" },
    { s: "8", d: "Infectologia", a: "Malária" },
    { s: "8", d: "Endocrino", a: "Diabetes Mellitus - Complicações Agudas" },
    { s: "8", d: "Nefrologia", a: "Doença Renal Crônica (DRC) - Parte II" },
    { s: "8", d: "Neuro", a: "Coma e Alterações da Consciência" },

    { s: "9", d: "Pediatria", a: "Reanimação neonatal" },
    { s: "9", d: "Cirurgia", a: "Abdome Agudo Inflamatório - Apendicite Aguda" },
    { s: "9", d: "Preventiva", a: "Processos de Descentralização e Regionalização do SUS" },
    { s: "9", d: "Ginecologia", a: "Pólipos Uterinos" },
    { s: "9", d: "Obstetrícia", a: "Partograma e Distocias" },
    { s: "9", d: "Cardiologia", a: "Insuficiência Cardíaca (Parte 2): Tratamento" },

    { s: "10", d: "Pediatria", a: "Distúrbios Respiratórios do Período Neonatal" },
    { s: "10", d: "Cirurgia", a: "Abdome Agudo Inflamatório - Colecistite e Colangite Aguda" },
    { s: "10", d: "Infectologia", a: "Síndrome Febril Íctero-Hemorrágica" },
    { s: "10", d: "Endocrino", a: "Diabetes Mellitus - Complicações Crônicas" },
    { s: "10", d: "Gastro", a: "Anatomofisiologia Gástrica, Gastrites, Gastroparesia e Dispepsia Funcional" },
    { s: "10", d: "Reumato", a: "Introdução à Reumatologia" },

    { s: "11", d: "Pediatria", a: "Distúrbios Metabólicos Neonatais" },
    { s: "11", d: "Cirurgia", a: "Abdome Agudo Inflamatório - Diverticulite Aguda" },
    { s: "11", d: "Preventiva", a: "Atenção Primária à Saúde" },
    { s: "11", d: "Ginecologia", a: "Dor Pélvica Crônica e Dismenorreia" },
    { s: "11", d: "Obstetrícia", a: "Assistência ao Parto" },
    { s: "11", d: "Cardiologia", a: "Insuficiência Cardíaca Aguda" },

    { s: "12", d: "Pediatria", a: "Infecções Congênitas" },
    { s: "12", d: "Cirurgia", a: "Abdome Agudo Perfurativo" },
    { s: "12", d: "Ginecologia", a: "Abdome Agudo em Ginecologia" },
    { s: "12", d: "Infectologia", a: "Neutropenia Febril e Febre de Origem Indeterminada" },
    { s: "12", d: "Endocrino", a: "Diabetes Mellitus - Hiperglicemia Hospitalar" },
    { s: "12", d: "Nefrologia", a: "Lesão Renal Aguda (LRA)" },

    { s: "13", d: "Pediatria", a: "Icterícia e Sepse Neonatal" },
    { s: "13", d: "Cirurgia", a: "Abdome Agudo Obstrutivo" },
    { s: "13", d: "Preventiva", a: "Políticas de Saúde" },
    { s: "13", d: "Obstetrícia", a: "Parto Vaginal Operatório" },
    { s: "13", d: "Cardiologia", a: "Dislipidemia e Estratificação de Risco Cardiovascular" },
    { s: "13", d: "Neuro", a: "Cefaleias" },

    { s: "14", d: "Pediatria", a: "Síndromes Genéticas, Erros Inatos do Metabolismo e da Imunidade" },
    { s: "14", d: "Cirurgia", a: "Abdome Agudo Vascular" },
    { s: "14", d: "Ginecologia", a: "Assistência à Vítima de Violência Sexual" },
    { s: "14", d: "Infectologia", a: "HIV" },
    { s: "14", d: "Endocrino", a: "Perioperatório - Controle Glicêmico e Manejo dos Glicocorticóides" },
    { s: "14", d: "Gastro", a: "Doença Ulcerosa Péptica, IBPs e H. Pylori" },

    { s: "15", d: "Pediatria", a: "Pneumonias na Infância" },
    { s: "15", d: "Cirurgia", a: "Abdome Agudo Hemorrágico" },
    { s: "15", d: "Preventiva", a: "Medicina de Família e Comunidade" },
    { s: "15", d: "Obstetrícia", a: "Indução do Parto e Pós-Datismo" },
    { s: "15", d: "Cardiologia", a: "Doença Arterial Coronariana Estável (DAC Estável)" },
    { s: "15", d: "Pneumo", a: "Derrame Pleural" },

    { s: "16", d: "Pediatria", a: "Bronquiolite" },
    { s: "16", d: "Cirurgia", a: "Medicina Perioperatória" },
    { s: "16", d: "Ginecologia", a: "Sangramento Uterino Anormal" },
    { s: "16", d: "Infectologia", a: "Endocardite Bacteriana - Endocardite Infecciosa" },
    { s: "16", d: "Endocrino", a: "Tireoide - Fisiologia, Semiologia e Avaliação Diagnóstica" },
    { s: "16", d: "Nefrologia", a: "Infecção do Trato Urinário" },

    { s: "17", d: "Pediatria", a: "Coqueluche" },
    { s: "17", d: "Cirurgia", a: "Resposta Endócrino-Metabólica ao Trauma" },
    { s: "17", d: "Preventiva", a: "Saúde do Idoso" },
    { s: "17", d: "Ginecologia", a: "Amenorreia" },
    { s: "17", d: "Obstetrícia", a: "Hemorragia Pós-Parto" },
    { s: "17", d: "Cardiologia", a: "SCASSST - Síndrome Coronária Aguda Sem Supra do Segmento ST" },

    { s: "18", d: "Pediatria", a: "Asma" },
    { s: "18", d: "Cirurgia", a: "Nutrição em Cirurgia e Aceleração da Recuperação Pós-Operatória" },
    { s: "18", d: "Infectologia", a: "Arboviroses (Dengue, Chikungunya e Zika)" },
    { s: "18", d: "Endocrino", a: "Tireoide - Hipotireoidismo" },
    { s: "18", d: "Gastro", a: "Anatomia e Fisiologia do Pâncreas e Neoplasias Pancreáticas" },
    { s: "18", d: "Neuro", a: "Demências" },

    { s: "19", d: "Pediatria", a: "Fibrose Cística" },
    { s: "19", d: "Cirurgia", a: "Complicações Pós-Operatórias" },
    { s: "19", d: "Preventiva", a: "Ética Médica" },
    { s: "19", d: "Ginecologia", a: "Síndrome dos Ovários Policísticos" },
    { s: "19", d: "Obstetrícia", a: "Infecção Puerperal" },
    { s: "19", d: "Cardiologia", a: "IAMCSST (Infarto Agudo do Miocárdio com Supradesnivelamento de Segmento ST)" },

    { s: "20", d: "Pediatria", a: "Doenças Exantemáticas" },
    { s: "20", d: "Cirurgia", a: "Cicatrização de Feridas" },
    { s: "20", d: "Infectologia", a: "Pneumonias Bacterianas" },
    { s: "20", d: "Endocrino", a: "Tireoide - Tireotoxicose: Diagnóstico, Etiologia, Tratamento" },
    { s: "20", d: "Nefrologia", a: "Distúrbios Ácido-Básicos" },
    { s: "20", d: "Pneumo", a: "Doença Pulmonar Obstrutiva Crônica (DPOC)" },

    { s: "21", d: "Pediatria", a: "Tuberculose na Infância" },
    { s: "21", d: "Cirurgia", a: "Hérnias da Parede Abdominal" },
    { s: "21", d: "Preventiva", a: "Processo Saúde-Doença" },
    { s: "21", d: "Ginecologia", a: "Planejamento Familiar" },
    { s: "21", d: "Obstetrícia", a: "Sangramento da Primeira Metade" },
    { s: "21", d: "Cardiologia", a: "Semiologia Cardíaca" },

    { s: "22", d: "Pediatria", a: "Febre na Pediatria" },
    { s: "22", d: "Cirurgia", a: "Cirurgia Bariátrica e Metabólica" },
    { s: "22", d: "Ginecologia", a: "Climatério e Terapia Hormonal" },
    { s: "22", d: "Infectologia", a: "Animais Peçonhentos" },
    { s: "22", d: "Endocrino", a: "Obesidade e Síndrome Metabólica" },
    { s: "22", d: "Gastro", a: "Pancreatite Aguda e Crônica" },

    { s: "23", d: "Pediatria", a: "Cardiopatias Congênitas" },
    { s: "23", d: "Cirurgia", a: "Vesícula e Vias Biliares" },
    { s: "23", d: "Preventiva", a: "Medidas de Saúde Coletiva - Indicadores de Morbidade" },
    { s: "23", d: "Obstetrícia", a: "Sangramento da Segunda Metade" },
    { s: "23", d: "Cardiologia", a: "Fibrilação e Flutter Atrial" },
    { s: "23", d: "Neuro", a: "Epilepsias" },

    { s: "24", d: "Pediatria", a: "Diarreia" },
    { s: "24", d: "Cirurgia", a: "Proctologia" },
    { s: "24", d: "Ginecologia", a: "Infertilidade Conjugal" },
    { s: "24", d: "Infectologia", a: "Sepse" },
    { s: "24", d: "Endocrino", a: "Metabolismo Ósseo e Mineral - Hipercalcemia" },
    { s: "24", d: "Nefrologia", a: "Análise da Gasometria Arterial" },

    { s: "25", d: "Pediatria", a: "Doença do Refluxo Gastroesofágico em Pediatria" },
    { s: "25", d: "Cirurgia", a: "Cirurgia Infantil - Parte I" },
    { s: "25", d: "Preventiva", a: "Medidas de Saúde Coletiva - Indicadores de Mortalidade" },
    { s: "25", d: "Obstetrícia", a: "Prematuridade e Trabalho de Parto Prematuro" },
    { s: "25", d: "Cardiologia", a: "Taquiarritmias" },
    { s: "25", d: "Pneumo", a: "Tromboembolismo Pulmonar (TEP)" },

    { s: "26", d: "Pediatria", a: "Infecção de Trato Urinário em Pediatria" },
    { s: "26", d: "Cirurgia", a: "Cirurgia Infantil - Parte II" },
    { s: "26", d: "Ginecologia", a: "Síndrome Pré-Menstrual" },
    { s: "26", d: "Infectologia", a: "Micoses Invasivas" },
    { s: "26", d: "Endocrino", a: "Metabolismo Ósseo e Mineral - Hipocalcemia" },
    { s: "26", d: "Gastro", a: "Anatomia e Fisiologia do Cólon e Síndrome do Intestino Irritável" },

    { s: "27", d: "Pediatria", a: "Doença de Kawasaki" },
    { s: "27", d: "Cirurgia", a: "Cirurgia Infantil - Parte III" },
    { s: "27", d: "Preventiva", a: "Medidas de Saúde Coletiva - Indicadores Demográficos" },
    { s: "27", d: "Ginecologia", a: "Cervicites" },
    { s: "27", d: "Obstetrícia", a: "Rotura Prematura de Membranas" },
    { s: "27", d: "Cardiologia", a: "Bradiarritmias" },

    { s: "28", d: "Pediatria", a: "Febre Reumática" },
    { s: "28", d: "Cirurgia", a: "Cirurgia Vascular" },
    { s: "28", d: "Infectologia", a: "Meningites (Infecções do SNC)" },
    { s: "28", d: "Endocrino", a: "Metabolismo Ósseo e Mineral - Osteoporose e Doença de Paget" },
    { s: "28", d: "Nefrologia", a: "Doenças Glomerulares" },
    { s: "28", d: "Neuro", a: "Acidentes Vasculares Cerebrais" },

    { s: "29", d: "Pediatria", a: "Emergências Pediátricas" },
    { s: "29", d: "Cirurgia", a: "Urologia" },
    { s: "29", d: "Preventiva", a: "Processos Epidêmicos e Epidemiologia das Doenças Infecciosas" },
    { s: "29", d: "Ginecologia", a: "Doença Inflamatória Pélvica" },
    { s: "29", d: "Obstetrícia", a: "Abortamento de Repetição" },
    { s: "29", d: "Cardiologia", a: "Parada Cardiorrespiratória (PCR)" },

    { s: "30", d: "Pediatria", a: "Choque em Pediatria" },
    { s: "30", d: "Cirurgia", a: "Cirurgia Plástica" },
    { s: "30", d: "Infectologia", a: "Hepatoesplenomegalias Infecciosas" },
    { s: "30", d: "Endocrino", a: "Adrenal - Hipocortisolismo (Insuficiência Adrenal)" },
    { s: "30", d: "Gastro", a: "Distúrbios Disabsortivos" },
    { s: "30", d: "Pneumo", a: "Pneumologia Intensiva" },

    { s: "31", d: "Pediatria", a: "Convulsão Febril" },
    { s: "31", d: "Cirurgia", a: "Cirurgia Torácica" },
    { s: "31", d: "Preventiva", a: "Vigilância em Saúde" },
    { s: "31", d: "Ginecologia", a: "Úlceras Genitais" },
    { s: "31", d: "Obstetrícia", a: "Gestação Múltipla" },
    { s: "31", d: "Cardiologia", a: "Síncope" },

    { s: "32", d: "Pediatria", a: "Anafilaxia e Urticária" },
    { s: "32", d: "Cirurgia", a: "Temas Gerais em Cirurgia" },
    { s: "32", d: "Ginecologia", a: "Vulvovaginites" },
    { s: "32", d: "Infectologia", a: "Influenza" },
    { s: "32", d: "Endocrino", a: "Adrenal - Hipercortisolismo (Síndrome de Cushing)" },
    { s: "32", d: "Nefrologia", a: "Nefrolitíase" },

    { s: "33", d: "Pediatria", a: "Hiperplasia Adrenal Congênita" },
    { s: "33", d: "Preventiva", a: "Sistemas de Informação em Saúde" },
    { s: "33", d: "Obstetrícia", a: "Síndromes Hipertensivas da Gestação" },
    { s: "33", d: "Cardiologia", a: "Eletrocardiograma" },
    { s: "33", d: "Neuro", a: "Doenças Neuromusculares (Neuropatias, Miopatias, Junção, Neurônio Motor)" },
    { s: "33", d: "Reumato", a: "Artrite Reumatoide" },

    { s: "34", d: "Pediatria", a: "Alergia Alimentar" },
    { s: "34", d: "Ginecologia", a: "Rastreamento do Câncer de Colo Uterino" },
    { s: "34", d: "Infectologia", a: "Parasitoses" },
    { s: "34", d: "Endocrino", a: "Adrenal - Feocromocitoma, Hiperaldosteronismo e Incidentaloma" },
    { s: "34", d: "Gastro", a: "Doença Inflamatória Intestinal" },
    { s: "34", d: "Hemato", a: "Introdução ao Estudo das Anemias" },

    { s: "35", d: "Pediatria", a: "Obesidade Infantil e na Adolescência" },
    { s: "35", d: "Preventiva", a: "Pesquisa Epidemiológica e Medidas de Associação" },
    { s: "35", d: "Obstetrícia", a: "Diabetes Mellitus na Gestação" },
    { s: "35", d: "Cardiologia", a: "Síndromes Aórticas Agudas" },
    { s: "35", d: "Pneumo", a: "Asma" },
    { s: "35", d: "Reumato", a: "Espondiloartrites" },

    { s: "36", d: "Pediatria", a: "Constipação Intestinal" },
    { s: "36", d: "Ginecologia", a: "Câncer de Colo Uterino" },
    { s: "36", d: "Infectologia", a: "Covid 19" },
    { s: "36", d: "Endocrino", a: "Hipófise - Hiperprolactinemia" },
    { s: "36", d: "Nefrologia", a: "Distúrbios do Potássio" },
    { s: "36", d: "Hemato", a: "Anemias Microcíticas" },

    { s: "37", d: "Pediatria", a: "Desnutrição na Infância" },
    { s: "37", d: "Preventiva", a: "Testes Diagnósticos" },
    { s: "37", d: "Ginecologia", a: "Tumores Anexiais e Câncer de Ovário" },
    { s: "37", d: "Obstetrícia", a: "Sífilis na Gestação e Sífilis Congênitas" },
    { s: "37", d: "Cardiologia", a: "Choque" },
    { s: "37", d: "Neuro", a: "Distúrbios do Movimento" },

    { s: "38", d: "Pediatria", a: "Hipertensão Arterial na Criança e Adolescente" },
    { s: "38", d: "Infectologia", a: "Infecções Relacionadas à Assistência em Saúde" },
    { s: "38", d: "Endocrino", a: "Neoplasias Endócrinas Múltiplas" },
    { s: "38", d: "Gastro", a: "Hemorragia Digestiva Alta Varicosa" },
    { s: "38", d: "Reumato", a: "Artrites Microcristalinas" },
    { s: "38", d: "Hemato", a: "Anemias Macrocíticas" },

    { s: "39", d: "Pediatria", a: "Púrpura de Hennoch Schonlein-Vasculite por IGA" },
    { s: "39", d: "Preventiva", a: "Estatística Médica" },
    { s: "39", d: "Ginecologia", a: "Doenças de Vulva e Vagina" },
    { s: "39", d: "Obstetrícia", a: "Ultrassom em Obstetrícia" },
    { s: "39", d: "Cardiologia", a: "Cardiomiopatias" },
    { s: "39", d: "Psiquiatria", a: "Dependência Química" },

    { s: "40", d: "Pediatria", a: "Artrite Idiopática Juvenil" },
    { s: "40", d: "Infectologia", a: "Raiva, Tétano, Mordedura e Arranhadura Animal" },
    { s: "40", d: "Nefrologia", a: "Distúrbios do Sódio - Disnatremias" },
    { s: "40", d: "Pneumo", a: "Neoplasias Pulmonares" },
    { s: "40", d: "Reumato", a: "Artropatias Infecciosas" },
    { s: "40", d: "Hemato", a: "Anemias Hemolíticas" },

    { s: "41", d: "Pediatria", a: "Tópicos em Pediatria" },
    { s: "41", d: "Preventiva", a: "Bases de Saúde do Trabalhador e Normas Regulamentadoras" },
    { s: "41", d: "Ginecologia", a: "Câncer do Corpo do Útero" },
    { s: "41", d: "Obstetrícia", a: "Vitalidade Fetal" },
    { s: "41", d: "Neuro", a: "Traumatismo Cranioencefálico" },
    { s: "41", d: "Dermato", a: "Histologia e Fisiologia da Pele e Lesões Elementares" },

    { s: "42", d: "Ginecologia", a: "Doenças Benignas da Mama" },
    { s: "42", d: "Infectologia", a: "Sífilis e Outras ISTs" },
    { s: "42", d: "Gastro", a: "Hemorragia Digestiva Alta Não Varicosa" },
    { s: "42", d: "Reumato", a: "Vasculites" },
    { s: "42", d: "Hemato", a: "Anemias Associadas a Condições Não Hematológicas" },
    { s: "42", d: "Psiquiatria", a: "Transtornos do Humor" },
    { s: "42", d: "Dermato", a: "Dermatoses Infecciosas" },

    { s: "43", d: "Obstetrícia", a: "Alteração do Volume de Líquido Amniótico" },
    { s: "43", d: "Reumato", a: "Doenças Autoimunes do Tecido Conjuntivo - Parte 1" },
    { s: "43", d: "Hemato", a: "Hemostasia I: Conceitos Básicos e Anticoagulantes" },
    { s: "43", d: "Psiquiatria", a: "Transtornos de Ansiedade" },
    { s: "43", d: "Gastro", a: "Introdução a Hepatologia" },
    { s: "43", d: "Dermato", a: "Hanseníase" },
    { s: "43", d: "Ortopedia", a: "Doenças da Coluna Vertebral" },
    { s: "43", d: "Otorrino", a: "Infecções de Vias Aéreas Superiores - Parte I" },

    { s: "44", d: "Ginecologia", a: "Rastreamento do Câncer de Mama" },
    { s: "44", d: "Nefrologia", a: "Túbulo-Interstício Renal" },
    { s: "44", d: "Reumato", a: "Doenças Autoimunes do Tecido Conjuntivo - Parte 2" },
    { s: "44", d: "Hemato", a: "Hemostasia II: Doenças Hemostáticas" },
    { s: "44", d: "Psiquiatria", a: "Transtornos Psicóticos" },
    { s: "44", d: "Gastro", a: "Hepatites Virais" },
    { s: "44", d: "Dermato", a: "Oncologia Cutânea (Câncer de Pele)" },
    { s: "44", d: "Ortopedia", a: "Doenças do Ombro e Cotovelo" },
    { s: "44", d: "Otorrino", a: "Infecções de Vias Aéreas Superiores - Parte II" },

    { s: "45", d: "Ginecologia", a: "Câncer de Mama" },
    { s: "45", d: "Obstetrícia", a: "Restrição de Crescimento Fetal e Óbito Fetal" },
    { s: "45", d: "Neuro", a: "Distúrbios do Sono" },
    { s: "45", d: "Reumato", a: "Doenças do Osso e da Cartilagem" },
    { s: "45", d: "Hemato", a: "Leucemias Agudas" },
    { s: "45", d: "Psiquiatria", a: "Intoxicações Exógenas" },
    { s: "45", d: "Dermato", a: "Dermatoses Eczematosas" },
    { s: "45", d: "Ortopedia", a: "Doenças da Mão e Síndromes Compressivas" },
    { s: "45", d: "Otorrino", a: "Infecções de Vias Aéreas Superiores - Parte III" },
    { s: "45", d: "Oftalmo", a: "Síndrome do Olho Vermelho" },

    { s: "46", d: "Ginecologia", a: "Incontinência Urinária" },
    { s: "46", d: "Gastro", a: "Hemorragia Digestiva Baixa" },
    { s: "46", d: "Reumato", a: "Síndromes Dolorosas Crônicas" },
    { s: "46", d: "Hemato", a: "Leucemias Crônicas, Linfomas, Mielodisplasias" },
    { s: "46", d: "Psiquiatria", a: "Psiquiatria Infantil" },
    { s: "46", d: "Gastro", a: "Cirrose Hepática" },
    { s: "46", d: "Dermato", a: "Farmacodermias" },
    { s: "46", d: "Ortopedia", a: "Oncologia Ortopédica e Osteomielite" },
    { s: "46", d: "Otorrino", a: "Otoneurologia, Vertigens e Audiologia" },
    { s: "46", d: "Oftalmo", a: "Córnea e Cristalino" },

    { s: "47", d: "Ginecologia", a: "Prolapso de Órgãos Pélvicos" },
    { s: "47", d: "Obstetrícia", a: "Infecções Congênitas na Gestação" },
    { s: "47", d: "Gastro", a: "Neoplasias de Estômago e Esôfago" },
    { s: "47", d: "Reumato", a: "Reumatologia Pediátrica" },
    { s: "47", d: "Hemato", a: "Mieloma Múltiplo (Gamopatias Monoclonais)" },
    { s: "47", d: "Psiquiatria", a: "Transtornos Alimentares" },
    { s: "47", d: "Dermato", a: "Dermatoses Papuloescamosas" },
    { s: "47", d: "Ortopedia", a: "Quadril Pediátrico" },
    { s: "47", d: "Otorrino", a: "Cirurgia de Cabeça e Pescoço - Laringologia, Apneia" },
    { s: "47", d: "Ortopedia", a: "Ombro e Joelho Pediátrico" },

    { s: "48", d: "Gastro", a: "Polipose Intestinal e Câncer Colorretal" },
    { s: "48", d: "Reumato", a: "Miscelânea" },
    { s: "48", d: "Hemato", a: "Medicina Transfusional" },
    { s: "48", d: "Psiquiatria", a: "Transtornos de Personalidade" },
    { s: "48", d: "Gastro", a: "Outras Causas de Hepatopatia Crônica" },
    { s: "48", d: "Dermato", a: "Dermatoses Vesicobolhosas" },
    { s: "48", d: "Ortopedia", a: "Desenvolvimento Ortopédico da Criança" },
    { s: "48", d: "Otorrino", a: "Cirurgia de Cabeça e Pescoço - Nódulos Tireoide" },
    { s: "48", d: "Ortopedia", a: "Maus Tratos" },
    { s: "48", d: "Oftalmo", a: "Glaucoma" },

    { s: "49", d: "Obstetrícia", a: "Aloimunização Materna e Doença Hemolítica Perinatal" },
    { s: "49", d: "Neuro", a: "Doenças Desmielinizantes e Encefalites Autoimunes" },
    { s: "49", d: "Psiquiatria", a: "Psicofarmacologia" },
    { s: "49", d: "Gastro", a: "Hepatopatias Autoimunes" },
    { s: "49", d: "Psiquiatria", a: "TOC, Transtornos Somáticos, Dissociativos e Estresse" },
    { s: "49", d: "Gastro", a: "Complicações da Cirrose Hepática" },
    { s: "49", d: "Dermato", a: "Síndromes Verrucosas" },
    { s: "49", d: "Ortopedia", a: "Conceitos Básicos do Trauma Ortopédico" },
    { s: "49", d: "Otorrino", a: "Cirurgia de Cabeça e Pescoço - Neoplasias Benignas e Malignas" },
    { s: "49", d: "Ortopedia", a: "Fratura Exposta" },

    { s: "50", d: "Psiquiatria", a: "Psicopatologia" },
    { s: "50", d: "Gastro", a: "Síndrome Hepatorrenal e Síndrome Hepatopulmonar" },
    { s: "50", d: "Dermato", a: "Piodermites" },
    { s: "50", d: "Ortopedia", a: "Complicações do Trauma Ortopédico" },
    { s: "50", d: "Psiquiatria", a: "Psiquiatria Social e Reforma Psiquiátrica" },
    { s: "50", d: "Gastro", a: "Tumores Hepáticos" },
    { s: "50", d: "Dermato", a: "Miscelânea" },
    { s: "50", d: "Ortopedia", a: "Fraturas e Luxações" },
    { s: "50", d: "Oftalmo", a: "Distúrbios da Refração" },
    { s: "50", d: "Ortopedia", a: "Politrauma Ortopédico" },
];

export const ESTRATEGIA_SCHEDULE: ScheduleItem[] = RAW_DATA.map(item => ({
    id: generateId(item.s, item.d, item.a),
    bloco: item.s,
    grandeArea: mapGrandeArea(item.d),
    disciplina: item.d,
    aula: item.a,
    professor: "", // Empty as requested/unavailable
    importancia: "" // Empty as requested/unavailable
}));
